spring:
  data:
    mongodb:
      host: 192.168.8.10
      port: 27017
      database: ngom_dev
      username: ngom_dev
      password: ngom!@#$%^789
  redis:
    host: 192.168.8.10
    port: 6379
    database: 5
    password: ngom123!@#
    pool:
      max-active: 600  # 连接池最大连接数（使用负值表示没有限制）
      max-idle: 300    # 连接池中的最大空闲连接
      max-wait: -60000   # 连接池最大阻塞等待时间（使用负值表示没有限制）
      min-idle: 10    # 连接池中的最小空闲连接
  jpa:
    show-sql: true


#druid
druid:
    url: jdbc:mysql://192.168.8.10:3306/ngot_dev?characterEncoding=UTF-8@&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
    username: root
    password: wb123!@#
    initial-size: 5
    min-idle: 1
    max-active: 100
    test-on-borrow: true
#mybatis
mybatis:
    type-aliases-package: ngom.domain
    mapper-locations: classpath:mapper/*.xml

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

ngo:
  image:
    url: http://192.168.8.12:8080/pictures/ngoHeads/


info:
  image:
    fixed-url: /usr/local/pictures
    info-url: /article/image
    base-url: http://192.168.8.12:8080
    picture-url: /pictures/